# Utiliza una imagen base con soporte para .NET Core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo .csproj y restaura las dependencias
COPY *.csproj .
RUN dotnet restore

# Copia todo el contenido del proyecto
COPY . .

# Compila la aplicación
RUN dotnet build --configuration Release --no-restore

# Publica la aplicación
RUN dotnet publish --configuration Release --no-build --output /app/publish

# Configura el contenedor para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Define la variable de entorno para el puerto
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000

ENTRYPOINT ["dotnet", "MicroservicioTest.dll"]